

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./utils/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://library_user:library_password@db:5432/library_db
    depends_on:
      - db
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  api-fixtures:
    build: .
    environment:
      - DATABASE_URL=postgresql://library_user:library_password@db:5432/library_db
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "sleep 5 && python utils/generate_fixtures.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: